// COMMENT: These are the states for the startup of the app.
export const startState = {
  ONBOARDING_VERIFICATION: 'ONBOARDING_VERIFY_EMAIL',
  ONBOARDING_INTRODUCTION: 'ONBOARDING_DEFINE_NAME',
  ONBOARDING_INTEGRATIONS: 'ONBOARDING_SETUP_INTEGRATION',
  ONBOARDING_GUIDE: 'ONBOARDING_GUIDE',
  NO_INTEGRATIONS: 'NO_INTEGRATIONS',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  INVITATION_INTRODUCTION: 'INVITED_DEFINE_NAME',
};
